environment:
   matrix:
     - nodejs_version: "Current"

cache:
  - 'node_modules -> yarn.lock'
  - '%LOCALAPPDATA%\\Yarn -> yarn.lock'

build: off

skip_branch_with_pr: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn --version
  - yarn install

test_script:
  - yarn test
